# Generated by Django 3.0.6 on 2020-05-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200510_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aula', to='courses.Course', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='None/None/materials'),
        ),
    ]
